/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ch09;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class FrmStudent extends javax.swing.JFrame {
    Vector<Student> data; //数据
    Vector data2; //用于在表格中显式数据
    Vector title=new Vector(); //表头
    //定义默认的表格模式
    DefaultTableModel dtm=new DefaultTableModel();
    //定义JTable
    JTable tbl=new JTable(dtm);
    //定义带滚动条的面板
    JScrollPane scp=new JScrollPane();
    int row=0;
    /**
     * Creates new form FrmStudent
     */
    public FrmStudent() {
        initComponents();
        //调用DBCon里查询数据的方法
       // data=DBCon.queryStudents("Select * from Student");
       
        //显式表格
        scp.setViewportView(tbl);
        scp.setBounds(20,150,350,250);
        //加入到窗口的内容面板里
        this.getContentPane().add(scp);
        //准备表头
        title.add("学号");
        title.add("姓名");
        title.add("性别");
        title.add("生日");
        //准备数据
        data2=DBCon.queryVectorStudents("Select * from Student");
        //在表格显式数据
        showTableData();
        //给表格添加事件监听器注册方法
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt); //调用下面的表格事件处理方法
            }
        });
        
        
         //调用文本框显式数据
        showTextData2(row);
        
        //表格中的同行数据要被选中
        tbl.setRowSelectionInterval(row, row);
    }
   /* //在文本框显式数据
    void showTextData(int index){
        Student stu=data.get(index);
        txtStuID.setText(stu.stuId);
        txtStuName.setText(stu.stuName);
        txtBirthday.setText(stu.birth.substring(0,10));
        if(stu.sex.equals("男")){
            radMan.setSelected(true);
        }else{
            radWoman.setSelected(true);
        } 
    }*/
    //在文本框显式数据(调用二维Vector)
    void showTextData2(int index){
        Vector line=(Vector)data2.get(index);
        txtStuID.setText(line.get(0).toString());
        txtStuName.setText(line.get(1).toString());
        txtBirthday.setText(line.get(3).toString().substring(0,10));
        if(line.get(2).toString().equals("男")){
            radMan.setSelected(true);
        }else{
            radWoman.setSelected(true);
        } 
    }
    
    //在表格显式数据
    void showTableData(){
        //在表格显式数据
        dtm.setDataVector(data2, title);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpSex = new javax.swing.ButtonGroup();
        lblStuID = new javax.swing.JLabel();
        txtStuID = new javax.swing.JTextField();
        lblStuName = new javax.swing.JLabel();
        txtStuName = new javax.swing.JTextField();
        lblSex = new javax.swing.JLabel();
        radMan = new javax.swing.JRadioButton();
        radWoman = new javax.swing.JRadioButton();
        lblBirthday = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("学生信息管理");

        lblStuID.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblStuID.setText("学号");

        txtStuID.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

        lblStuName.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblStuName.setText("姓名");

        txtStuName.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

        lblSex.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblSex.setText("性别");

        btngrpSex.add(radMan);
        radMan.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        radMan.setText("男");

        btngrpSex.add(radWoman);
        radWoman.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        radWoman.setText("女");

        lblBirthday.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblBirthday.setText("生日");

        txtBirthday.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPre.setText("<");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">>");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStuID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStuID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSex)
                                .addGap(18, 18, 18)
                                .addComponent(radMan)
                                .addGap(18, 18, 18)
                                .addComponent(radWoman)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBirthday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBirthday))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStuName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLast)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStuID)
                    .addComponent(txtStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStuName)
                    .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radMan)
                    .addComponent(lblBirthday)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radWoman)
                    .addComponent(lblSex))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPre)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //下一条
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        row++;
        if(row>=data2.size()){
            row=data2.size()-1; //停在最后一条
            //弹出对话框
            JOptionPane.showMessageDialog(null,"已经是最后一条数据了","系统提示",JOptionPane.INFORMATION_MESSAGE);
        }
        //再次在文本框中显示数据
        showTextData2(row);
        //表格中的同行数据要被选中
        tbl.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_btnNextActionPerformed
    //上一条
    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        row--;
        if(row<0){
            row=0; //停在第一条数据
             //弹出对话框
            JOptionPane.showMessageDialog(null,"已经是第一条数据了","系统提示",JOptionPane.INFORMATION_MESSAGE);
        }
        //再次在文本框中显示数据
        showTextData2(row);
        //表格中的同行数据要被选中
        tbl.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        row=0;
        //再次在文本框中显示数据
        showTextData2(row);
        //表格中的同行数据要被选中
        tbl.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        row=data2.size()-1;
        //再次在文本框中显示数据
        showTextData2(row);
        //表格中的同行数据要被选中
        tbl.setRowSelectionInterval(row, row);
    }//GEN-LAST:event_btnLastActionPerformed
    //表格点击事件处理方法
    private void tblMouseClicked(java.awt.event.MouseEvent evt) {                                 
        //获得鼠标选中的行号（索引）
        row=tbl.getSelectedRow();
        //再次在文本框中显示数据
        showTextData2(row);
    }     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.ButtonGroup btngrpSex;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblStuID;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JRadioButton radMan;
    private javax.swing.JRadioButton radWoman;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtStuID;
    private javax.swing.JTextField txtStuName;
    // End of variables declaration//GEN-END:variables
}
